// Server-side data access. The JSON is generated by `npm run data`.
import "server-only";
import cardsJson from "@/data/cards.json";
import collectionJson from "@/data/collection.json";
import type {
  Card,
  CardDataset,
  CollectionCard,
  CollectionDataset,
} from "./types";

const cardData = cardsJson as unknown as CardDataset;
const collectionData = collectionJson as unknown as CollectionDataset;

export function getAllCards(): Card[] {
  return cardData.cards;
}

export function getCardById(id: number): Card | undefined {
  return cardData.cards.find((c) => c.id === id);
}

export function getCollection(): CollectionCard[] {
  return collectionData.cards;
}

export function getDatasetMeta() {
  return {
    cards: cardData.count,
    collection: collectionData.count,
    generatedAt: cardData.generatedAt,
  };
}
